// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DeletarClienteVlidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void deletarClienteVlido() {
    driver.Navigate().GoToUrl("https://localhost:7245/");
    driver.Manage().Window.Size = new System.Drawing.Size(697, 728);
    driver.FindElement(By.LinkText("Cliente")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(4) a:nth-child(3)")).Text, Is.EqualTo("Delete"));
    driver.FindElement(By.CssSelector("tr:nth-child(4) a:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
  }
}
