// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InserirClienteVlidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void inserirClienteVlido() {
    driver.Navigate().GoToUrl("https://localhost:7245/");
    driver.Manage().Window.Size = new System.Drawing.Size(697, 728);
    driver.FindElement(By.LinkText("Cliente")).Click();
    Assert.That(driver.FindElement(By.LinkText("Create New")).Text, Is.EqualTo("Create New"));
    driver.FindElement(By.LinkText("Create New")).Click();
    driver.FindElement(By.Id("Id")).Click();
    driver.FindElement(By.Id("Id")).SendKeys("4");
    driver.FindElement(By.Id("IdAssinatura")).Click();
    driver.FindElement(By.Id("IdAssinatura")).SendKeys("1");
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("Laila Estefane Santos Torres");
    driver.FindElement(By.Id("Celular")).Click();
    driver.FindElement(By.Id("Celular")).SendKeys("79991765544");
    driver.FindElement(By.Id("Cpf")).Click();
    driver.FindElement(By.Id("Cpf")).SendKeys("063.383.292");
    driver.FindElement(By.Id("Cep")).Click();
    driver.FindElement(By.Id("Cep")).SendKeys("49503699");
    driver.FindElement(By.Id("Telefone")).Click();
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Bairro")).Click();
    driver.FindElement(By.Id("Rua")).Click();
    driver.FindElement(By.Id("Rua")).SendKeys("Rua Manoel das Neves Barreto");
    driver.FindElement(By.Id("NumResidencia")).Click();
    driver.FindElement(By.Id("PontoReferencia")).Click();
    driver.FindElement(By.Id("PontoReferencia")).SendKeys("Perto do Eu amo Itabaina");
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("lailaestefane1233030@gmail.com");
    driver.FindElement(By.Id("Bairro")).Click();
    driver.FindElement(By.Id("Bairro")).SendKeys("Anízio Amancio de Oliveira");
    driver.FindElement(By.Id("NumResidencia")).Click();
    driver.FindElement(By.Id("NumResidencia")).SendKeys("305");
    driver.FindElement(By.Id("TipoPessoa")).Click();
    {
      var dropdown = driver.FindElement(By.Id("TipoPessoa"));
      dropdown.FindElement(By.XPath("//option[. = 'Cliente']")).Click();
    }
    driver.FindElement(By.Id("Cpf")).Click();
    driver.FindElement(By.Id("Cpf")).SendKeys("06338329280");
    driver.FindElement(By.Id("DataNascimento")).Click();
    driver.FindElement(By.Id("DataNascimento")).SendKeys("0002-10-08");
    driver.FindElement(By.Id("DataNascimento")).SendKeys("0020-10-08");
    driver.FindElement(By.Id("DataNascimento")).SendKeys("0200-10-08");
    driver.FindElement(By.Id("DataNascimento")).SendKeys("2000-10-08");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
  }
}
