// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AlterarServioVlidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void alterarServioVlido() {
    driver.Navigate().GoToUrl("https://localhost:7245/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.LinkText("Ofertar Serviço")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".border-b:nth-child(3) .border")).Text, Is.EqualTo("⚙️\\\\nModificar Serviço"));
    driver.FindElement(By.CssSelector(".border-b:nth-child(3) .border")).Click();
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("Mecanico");
    {
      string value = driver.FindElement(By.CssSelector(".bg-primary")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("Salvar"));
    }
    driver.FindElement(By.CssSelector(".bg-primary")).Click();
  }
}
