// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InserirServioVlidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void inserirServioVlido() {
    driver.Navigate().GoToUrl("https://localhost:7245/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.LinkText("Ofertar Serviço")).Click();
    Assert.That(driver.FindElement(By.LinkText("Criar Novo Serviço")).Text, Is.EqualTo("Criar Novo Serviço"));
    driver.FindElement(By.LinkText("Criar Novo Serviço")).Click();
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("Encanador");
    driver.FindElement(By.Id("DataHoraSolicitacao")).Click();
    driver.FindElement(By.Id("DataHoraSolicitacao")).SendKeys("0002-02-19");
    driver.FindElement(By.Id("DataHoraSolicitacao")).SendKeys("0020-02-19");
    driver.FindElement(By.Id("DataHoraSolicitacao")).SendKeys("0202-02-19");
    driver.FindElement(By.Id("DataHoraSolicitacao")).SendKeys("2025-02-19");
    driver.FindElement(By.Id("Valor")).Click();
    driver.FindElement(By.Id("Valor")).SendKeys("280");
    driver.FindElement(By.Id("IdProfissional")).SendKeys("1");
    driver.FindElement(By.Id("IdProfissional")).Click();
    driver.FindElement(By.Id("IdTipoServico")).SendKeys("1");
    driver.FindElement(By.Id("IdTipoServico")).Click();
    driver.FindElement(By.Id("IdTipoServico")).SendKeys("2");
    driver.FindElement(By.Id("IdTipoServico")).Click();
    driver.FindElement(By.Id("IdAreaAtuacao")).SendKeys("1");
    driver.FindElement(By.Id("IdAreaAtuacao")).Click();
    {
      string value = driver.FindElement(By.CssSelector(".bg-primary")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("Publicar Serviço"));
    }
    driver.FindElement(By.CssSelector(".bg-primary")).Click();
  }
}
