// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RemoverServioVlidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void removerServioVlido() {
    driver.Navigate().GoToUrl("https://localhost:7245/");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 816);
    driver.FindElement(By.LinkText("Ofertar Serviço")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".border-b:nth-child(3) .bg-red-600")).Text, Is.EqualTo("Apagar Serviço"));
    driver.FindElement(By.CssSelector(".border-b:nth-child(3) .bg-red-600")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".bg-green-600")).Text, Is.EqualTo("Apagar Serviço"));
    driver.FindElement(By.CssSelector(".bg-green-600")).Click();
  }
}
